Added unit tests for services
CrazyKamenwik/DimaBog pull request #19
Opened 2023-02-20 13:15 UTC by 5Ka-me

2023-02-20 14:07 UTC, moltenessence requested changes

2023-02-20 14:07 UTC, moltenessence commented on SkyDrive/SkyDrive.Tests/UnitTests/EventServiceTests.cs
> +            _mockRepository.Setup(x => x.GetById(3, CancellationToken.None)).ReturnsAsync(value: null);
what is '3'? it's not obvious. probably, move it to separate variable with proper name

2023-02-20 14:07 UTC, moltenessence commented on SkyDrive/SkyDrive.Tests/UnitTests/InstructorServiceTests.cs
> +            var instructorEntity = new InstructorEntity
Now stay it like that. But in future it would be better to use AutoData and your code will become much shorter

2023-02-21 11:15 UTC, stas1408123 approved these changes

2023-02-21 11:15 UTC, stas1408123 commented on SkyDrive/SkyDrive.Tests/FixtureCustomization/MyFixtureAttribute.cs
> +    public class MyFixtureAttribute : AutoDataAttribute
Rename

2023-02-21 11:20 UTC, Genresal approved these changes

2023-02-21 11:42 UTC, moltenessence approved these changes

2023-02-21 11:43 UTC, merged