Add business logic to controllers
CrazyKamenwik/DimaBog pull request #4
Opened 2023-02-06 13:40 UTC by 5Ka-me

2023-02-06 14:01 UTC, Genresal approved these changes

2023-02-06 14:01 UTC, Genresal commented on SkyDrive/SkyDrive/Controllers/InstructorController.cs
> +
Possibly makes sense to move an entity exists checking logic to a separate auxiliary method, smth like IsEntityExists(int id), later you can move that method to your future services or repositories.

2023-02-06 14:09 UTC, CrazyKamenwik requested changes

2023-02-06 14:09 UTC, CrazyKamenwik commented on SkyDrive/SkyDrive/Controllers/EventController.cs
> +        }
Yeah, that way just "return entity"

2023-02-07 09:08 UTC, CrazyKamenwik approved these changes

2023-02-07 09:10 UTC, blackberts approved these changes

2023-02-07 09:25 UTC, merged